version: 2.1

orbs:
  maven: circleci/maven@1.2.0

executors:
  jdk11:
    docker:
      - image: cimg/openjdk:11.0.12

jobs:
  store_javadoc:
    executor: jdk11
    steps:
      - store_artifacts:
          path: ./target/site/apidocs

workflows:
  test:
    jobs:
      - maven/test:
          command: "-X verify javadoc:javadoc"
          executor: jdk11
      - store_javadoc:
          requires:
            - maven/test
